"""Oracle 数据库适配器。"""
from __future__ import annotations

from .base import DBAdapter

QUERY_SETS: dict = {
    "basic_info": {
        "label": "基础信息",
        "queries": {
            "version": "SELECT BANNER FROM V$VERSION WHERE ROWNUM=1;",
            "version_detail": "SELECT * FROM V$VERSION;",
            "non_default_params": "SELECT NAME, VALUE, ISDEFAULT FROM V$PARAMETER WHERE ISDEFAULT='FALSE' AND NAME NOT LIKE '\\_%' ESCAPE '\\' AND ROWNUM<=50;",
        }
    },
    "db_info": {
        "label": "数据库信息",
        "queries": {
            "database_info": "SELECT NAME, DBID, CREATED, LOG_MODE, OPEN_MODE, DATABASE_ROLE, FLASHBACK_ON, FORCE_LOGGING FROM V$DATABASE;",
            "ha_slave_info": "SELECT DATABASE_ROLE, PROTECTION_MODE, PROTECTION_LEVEL FROM V$DATABASE;",
        }
    },
    "storage": {
        "label": "存储空间",
        "queries": {
            "effective_space": "SELECT ROUND(SUM(BYTES)/1024/1024/1024,2)||' GB' AS EFFECTIVE_SPACE FROM DBA_DATA_FILES;",
            "schema_space": "SELECT OWNER, ROUND(SUM(BYTES)/1024/1024,2)||' M' TOTAL_SPACE FROM DBA_SEGMENTS GROUP BY OWNER ORDER BY SUM(BYTES) DESC;",
            "tablespace_info": "SELECT TABLESPACE_NAME, ROUND(SUM(BYTES)/1024/1024,2) AS SIZE_MB, ROUND(SUM(MAXBYTES)/1024/1024,2) AS MAX_MB FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME ORDER BY TABLESPACE_NAME;",
            "datafile_info": "SELECT FILE_NAME, TABLESPACE_NAME, ROUND(BYTES/1024/1024,2)||' M' CURRENT_SIZE, ROUND(MAXBYTES/1024/1024,2)||' M' MAX_SIZE, AUTOEXTENSIBLE FROM DBA_DATA_FILES ORDER BY BYTES DESC;",
            "logfile_info": "SELECT GROUP#, THREAD#, SEQUENCE#, ROUND(BYTES/1024/1024)||' M' SIZE_MB, MEMBERS, STATUS FROM V$LOG;",
            "table_disk_space": "SELECT ROUND(SUM(BYTES)/1024/1024,2)||' MB' TABLE_SPACE FROM DBA_SEGMENTS WHERE SEGMENT_TYPE='TABLE';",
            "index_disk_space": "SELECT ROUND(SUM(BYTES)/1024/1024,2)||' MB' INDEX_SPACE FROM DBA_SEGMENTS WHERE SEGMENT_TYPE='INDEX';",
        }
    },
    "objects": {
        "label": "数据库对象统计",
        "queries": {
            "table_count_total": "SELECT COUNT(*) TOTAL_TABLE_NUM FROM DBA_TABLES WHERE OWNER NOT IN ('SYS','SYSTEM','XDB','WMSYS','OUTLN','DBSNMP','ORDSYS','ORDDATA','CTXSYS','MDSYS','OLAPSYS');",
            "table_count_by_user": "SELECT OWNER, COUNT(*) TABLE_COUNT FROM DBA_TABLES GROUP BY OWNER ORDER BY COUNT(*) DESC;",
            "index_count_total": "SELECT COUNT(*) TOTAL_INDEX_NUM FROM DBA_INDEXES WHERE OWNER NOT IN ('SYS','SYSTEM','XDB','WMSYS','OUTLN','DBSNMP','ORDSYS','ORDDATA','CTXSYS','MDSYS','OLAPSYS');",
            "index_count_by_user": "SELECT OWNER, COUNT(*) INDEX_COUNT FROM DBA_INDEXES GROUP BY OWNER ORDER BY COUNT(*) DESC;",
            "view_count_total": "SELECT COUNT(*) TOTAL_VIEW_NUM FROM DBA_VIEWS WHERE OWNER NOT IN ('SYS','SYSTEM','XDB','WMSYS','OUTLN','DBSNMP');",
            "proc_count_total": "SELECT COUNT(*) TOTAL_PROC_NUM FROM DBA_PROCEDURES WHERE OWNER NOT IN ('SYS','SYSTEM','XDB','WMSYS','OUTLN','DBSNMP');",
        }
    },
    "performance": {
        "label": "性能监控",
        "queries": {
            "session_count": "SELECT COUNT(*) AS CONNECTION_COUNT FROM V$SESSION;",
            "session_by_ip": "SELECT COUNT(*), MACHINE FROM V$SESSION GROUP BY MACHINE ORDER BY COUNT(*) DESC;",
            "deadlock_count": "SELECT COUNT(*) AS DEADLOCK_COUNT FROM V$LOCK WHERE BLOCK=1;",
            "wait_chains": "SELECT * FROM V$WAIT_CHAINS WHERE ROWNUM<=20;",
            "active_queries": "SELECT SID, SERIAL#, USERNAME, MACHINE, SQL_ID, STATUS, LAST_CALL_ET FROM V$SESSION WHERE STATUS='ACTIVE' AND USERNAME IS NOT NULL;",
            "non_auto_commit": "SELECT COUNT(*) AS ACTIVE_TRANSACTIONS FROM V$TRANSACTION;",
            "db_memory": "SELECT COMPONENT, CURRENT_SIZE/1024/1024||' MB' AS SIZE_MB, MIN_SIZE/1024/1024||' MB' MIN_MB, MAX_SIZE/1024/1024||' MB' MAX_MB FROM V$MEMORY_DYNAMIC_COMPONENTS WHERE CURRENT_SIZE>0;",
            "slow_sql": "SELECT * FROM (SELECT ELAPSED_TIME/1000000 AS TIME_S, SQL_TEXT FROM V$SQL WHERE ELAPSED_TIME/1000000 > 0.5 AND SQL_TEXT NOT LIKE '%V$SQL%' ORDER BY ELAPSED_TIME DESC) WHERE ROWNUM<=20;",
        }
    },
}


class OracleAdapter(DBAdapter):
    db_type = "oracle"
    label = "Oracle"
    default_port = 1521
    default_user = "system"
    default_db = "ORCL"
    cli_tool = "sqlplus"
    cli_heredoc = False
    cli_win_file = True
    cli_no_if_not_exists = True
    query_sets = QUERY_SETS

    ddl_serial = "NUMBER GENERATED BY DEFAULT AS IDENTITY"
    ddl_boolean = "NUMBER(1)"
    ddl_timestamp = "TIMESTAMP"
    ddl_text = "CLOB"
    ddl_numeric = "NUMBER(10,3)"
    ddl_int = "NUMBER"
    ddl_varchar = "VARCHAR2"

    def sql_now(self) -> str:
        return "SYSDATE"

    def sql_interval(self, days: int) -> str:
        return f"SYSDATE - interval '{days}' day"

    def sql_to_char(self, col: str) -> str:
        return f"TO_CHAR({col},'YYYY-MM-DD HH24:MI:SS')"

    def sql_cast_ts(self, v: str) -> str:
        return f"TO_TIMESTAMP('{v}','YYYY-MM-DD HH24:MI:SS')"

    def sql_concat(self, a: str, b: str) -> str:
        return f"NVL({a},'')"

    def sql_from_dual(self) -> str:
        return "from dual"

    def sql_limit(self, n: int) -> str:
        return f"fetch first {n} rows only"
